# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty
baseurl: /my-blog

# Setup
title:            Movies and shit
tagline:          'Or, Find A Better Title'
description:      'For movies and things. Original Theme by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://chuckedup.github.io/

author:
  name:           'Jeel Shah'
  url:            http://chuckedup.github.io/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           http://chuckedup.github.io/my-blog
